
import com.sun.glass.events.KeyEvent;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
         getContentPane().setBackground(new java.awt.Color(204,204,255));
         this.setLocationRelativeTo(null);
        l1.setVisible(false);
        l2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        button_cancel = new javax.swing.JButton();
        button_Login = new javax.swing.JButton();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setForeground(new java.awt.Color(204, 0, 0));

        label_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(51, 51, 51));
        label_username.setText("Username:");

        label_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_password.setForeground(new java.awt.Color(51, 51, 51));
        label_password.setText("Password:");

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 0, 0));
        l1.setText("*");

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 0, 0));
        l2.setText("*");

        button_cancel.setBackground(new java.awt.Color(153, 153, 153));
        button_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_cancel.setForeground(new java.awt.Color(0, 102, 153));
        button_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-30.png"))); // NOI18N
        button_cancel.setText("CANCEL");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        button_cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                button_cancelKeyReleased(evt);
            }
        });

        button_Login.setBackground(new java.awt.Color(153, 153, 153));
        button_Login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_Login.setForeground(new java.awt.Color(0, 102, 153));
        button_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30.png"))); // NOI18N
        button_Login.setText("LOGIN");
        button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LoginActionPerformed(evt);
            }
        });
        button_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                button_LoginKeyReleased(evt);
            }
        });

        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-male-user-96.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(label_username)
                        .addGap(6, 6, 6)
                        .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(label_password)
                        .addGap(8, 8, 8)
                        .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(l2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(label_username))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(label_password))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LoginActionPerformed
        // TODO add your handling code here:
                if(tf_username.getText().equals("")){
            l1.setVisible(true);
        }else if(String.valueOf(jPasswordField_password.getPassword()).equals("")){
            l2.setVisible(true);
        }else{
           Connection con=MyConnection.getConnection();
           PreparedStatement stmt;
           PreparedStatement stm;
            try {
                stmt = con.prepareStatement("select * from login where username=? and password=?");
                stm=con.prepareStatement("select * from login where username=?");
                stmt.setString(1,tf_username.getText());
                stmt.setString(2,String.valueOf(jPasswordField_password.getPassword()));
                stm.setString(1, tf_username.getText());
                ResultSet rs=stmt.executeQuery();
                ResultSet ts=stm.executeQuery();
                if(rs.next()){
                    Welcome m=new Welcome();
                    m.setVisible(true);
                    m.setLocationRelativeTo(null);
                    m.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    if(ts.next()){
                        m.jLabel_name.setText("Welcome! '"+ts.getString(2).toUpperCase()+"' To Our Dashboard.");
                    }
                    m.jLabel_stcount.setText("Student Count: "+Integer.toString(MyFunction.count("student")));
                    m.jLabel_cocount.setText("Course Count: "+Integer.toString(MyFunction.count("course")));
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"NotConnected");
            }
           
        }

        
    }//GEN-LAST:event_button_LoginActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void button_LoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_LoginKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                    if(tf_username.getText().equals("")){
            l1.setVisible(true);
        }else if(String.valueOf(jPasswordField_password.getPassword()).equals("")){
            l2.setVisible(true);
        }else{
           Connection con=MyConnection.getConnection();
           PreparedStatement stmt;
           PreparedStatement stm;
            try {
                stmt = con.prepareStatement("select * from login where username=? and password=?");
                stm=con.prepareStatement("select * from login where username=?");
                stmt.setString(1,tf_username.getText());
                stmt.setString(2,String.valueOf(jPasswordField_password.getPassword()));
                stm.setString(1, tf_username.getText());
                ResultSet rs=stmt.executeQuery();
                ResultSet ts=stm.executeQuery();
                if(rs.next()){
                    Welcome m=new Welcome();
                    m.setVisible(true);
                    m.setLocationRelativeTo(null);
                    m.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    if(ts.next()){
                        m.jLabel_name.setText("Welcome! '"+ts.getString(2)+"' To Our Dashboard.");
                    }
                    m.jLabel_stcount.setText("Student Count: "+Integer.toString(MyFunction.count("student")));
                    m.jLabel_cocount.setText("Course Count: "+Integer.toString(MyFunction.count("course")));
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"NotConnected");
            }
           
        }

            
            
        }
    }//GEN-LAST:event_button_LoginKeyReleased

    private void button_cancelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_cancelKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            System.exit(0);
        }
    }//GEN-LAST:event_button_cancelKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Login;
    private javax.swing.JButton button_cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
